Add GPT::get_partition_byte_range
cecton/gptman pull request #76
Opened 2022-05-06 23:05 UTC by nicholasbishop

This method returns the range of bytes covered by a partition. This is
useful when directly accessing the partition data.

2022-05-07 07:10 UTC, cecton requested changes
Hello :wave: 

Thanks a lot for your PR! Very nice documentation and test. It's very well done and consistent with the rest of the library.

I'm sorry to have some remarks on it though... :disappointed: 

I'm also not sure if this is the best way to implement this as having a range would **also** be useful in sector size. For that case you can implement this on `GPTPartitionEntry` instead. The sector-to-byte conversion is easy to do but converting a `Range` itself is not unfortunately (I assume you don't intend to iterate over bytes right?) so we still need to implement something on `GPT`.

So I would see 2 methods:

* `fn range(&self) -> Result<RangeInclusive<u64>>` on `GPTPartitionEntry`
* `fn get_partition_byte_range(&self) -> Result<RangeInclusive<u64>>` on `GPT` that would call `range()` on the partition entry and multiply the beginning and the end of the iterator (and check for overflow).

2022-05-07 07:10 UTC, cecton commented on src/lib.rs
> +        Ok(start_byte..end_byte)
You could should RangeInclusive instead so you don't need to add 1 like that

2022-05-07 07:10 UTC, cecton commented on src/lib.rs
> +        let end_byte = (partition.ending_lba + 1) * self.sector_size;
Those multiplies can actually overflow and panic. You should probably add an error variant for overflow.

2022-05-07 15:42 UTC, nicholasbishop commented on src/lib.rs
> +        }
No strong opinion from me. I've updated the PR with option 2, adding a new `UnusedPartition` error variant.

2022-05-07 15:43 UTC, nicholasbishop commented on src/lib.rs
> +        let end_byte = (partition.ending_lba + 1) * self.sector_size;
Added a new `Error::Overflow` variant and switched these operations to use `u64::checked_*`.

2022-05-07 15:48 UTC, nicholasbishop commented on src/lib.rs
> +        Ok(start_byte..end_byte)
I've switched to `RangeInclusive` as suggested. This does avoid adding 1 for the `GPTPartitionEntry::range` case, but `GPT::get_partition_byte_range` still has to do some extra manipulation because we need the byte at the end of the end sector rather than the byte at the beginning. I've updated the code there and added a comment to clarify the arithmetic (and also switched it to `RangeInclusive` for consistency).

2022-05-07 15:50 UTC, nicholasbishop commented
Thanks for the detailed review! I've updated the PR, happy to make more adjustments as needed :)

2022-05-09 08:52 UTC, cecton requested changes
Sorry for the late reply :pray: 

A few minor adjustments/proposals from my side left. Thanks a lot for your time and your contribution!

2022-05-09 08:52 UTC, cecton commented on src/lib.rs
> +    #[error("partition not found")]
```suggestion
    /// An arithmetic operation overflowed.
    #[error("an arithmetic operation overflowed")]
```

2022-05-09 08:52 UTC, cecton commented on src/lib.rs
> +        }
This check should probably be moved to `fn range()`? wdyt?

2022-05-09 08:52 UTC, cecton commented on src/lib.rs
> +            .and_then(|v| v.checked_sub(1))
I guess we could remove one overflow check like this.

```suggestion
            .and_then(|v| v.checked_add(self.sector_size - 1))
```

2022-05-10 03:22 UTC, nicholasbishop commented on src/lib.rs
> +    #[error("partition not found")]
Fixed

2022-05-10 03:23 UTC, nicholasbishop commented on src/lib.rs
> +        }
Makes sense, I've updated it as suggested. That did require removing the partition number from the error, since the partition entry doesn't know its own number, but that's fine I think.

2022-05-10 03:23 UTC, nicholasbishop commented on src/lib.rs
> +            .and_then(|v| v.checked_sub(1))
Done

2022-05-10 05:42 UTC, cecton commented on src/lib.rs
> +        }
I didn't think about that :thinking: well... not a huge deal I guess

2022-05-10 05:44 UTC, cecton approved these changes

2022-05-10 05:44 UTC, merged

2022-05-10 05:50 UTC, cecton commented
Done: https://github.com/cecton/gptman/releases/tag/v0.8.4

Thanks again and have a great day!

2022-05-10 14:07 UTC, nicholasbishop commented
:+1: thanks!